//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopeyWinery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor
    {
        public int Id_labor { get; set; }
        public string Name { get; set; }
    }
}
