//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopeyWinery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lane()
        {
            this.Location_lane_Xref = new HashSet<Location_lane_Xref>();
        }
    
        public int Id_lane { get; set; }
        public string Name { get; set; }
        public Nullable<int> plant_quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location_lane_Xref> Location_lane_Xref { get; set; }
    }
}
