//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopeyWinery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_lane_Xref
    {
        public int Id_location_lane { get; set; }
        public Nullable<int> Id_location { get; set; }
        public Nullable<int> Id_lane { get; set; }
    
        public virtual Lane Lane { get; set; }
        public virtual Location Location { get; set; }
    }
}
