//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopeyWinery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int Task_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Number_hours { get; set; }
        public string Hour_type { get; set; }
        public int UserId { get; set; }
        public int Activity_Id { get; set; }
        public int Id_labor { get; set; }
        public int Id_location { get; set; }
        public Nullable<int> Ext_Attr_Labor_Value { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        public virtual Labor Labor { get; set; }
    }
}
